#!/usr/bin/python3
import matplotlib.pyplot as plt
from calc_mod import *
import argparse
parser=argparse.ArgumentParser()
parser.add_argument("-imname","--archivo",type=str,help="Nombre del archivo a procesar")
parser.add_argument("-hz","--frecuencia",type=float,help="Frecuencia de la lampara estroboscopica en hertz")
parser.add_argument("-dx","--pixel",type=float,help="Tamano de cada pixel en mm")
args=parser.parse_args() #args guarda las entradas
archivo=args.archivo 
hz=args.frecuencia
dx=args.pixel 
imagen=plt.imread(archivo)
bw=((imagen[:,:,0]/10+imagen[:,:,1]/10+imagen[:,:,2]/10)/3)*10
print(calc(bw,hz,dx))
if __name__ =="__main__":
    print("***")
   
